// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using diploma_strava_ex_api.Models.DBModels;

#nullable disable

namespace diploma_strava_ex_api.Migrations
{
    [DbContext(typeof(PlannerContext))]
    [Migration("20260503164259_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("diploma_strava_ex_api.Models.DBModels.PlannerItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Distance")
                        .HasColumnType("REAL");

                    b.Property<float>("Elevation")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("PlanDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlannerItems");
                });
#pragma warning restore 612, 618
        }
    }
}
