# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      Solution_Name: diploma_strava_ex_api      
    steps:            
    #npm install
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: 24
        package-manager-cache: false # Disable automatic npm caching if not required
    - run: npm ci
    - run: npm test
    
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    # Substitute production appsettings entries to appsettings json file
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: 'appsettings.json'
      env:
        Authentication.clientId: ${{ secrets.CLIENT_ID }}
        Authentication.clientSecret: ${{ secrets.CLIENT_SECRET }}
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
